baseURL: "https://anton.ohorodnyk.name/"
languageCode: "en-us"
title: "Anton Ohorodnyk"
copyright: "Anton Ohorodnyk All Rights Reserved"

disableLanguages: true
enableGitInfo: false
enableRobotsTXT: true

menu:
  main:
  - name: Home
    post:
    pre:
    url: /
    weight: 1
  - name: About
    post:
    pre:
    url: /about
    weight: 2
  - name: Topics
    post:
    pre:
    url: /topics
    weight: 4

params:
  meta:
    favicon:
      version: 1

module:
  imports:
    - path: github.com/necolas/normalize.css
      mounts:
        - source: normalize.css
          target: assets/css/normalize.css
    - path: github.com/FortAwesome/Font-Awesome
      mounts:
        - source: svgs
          target: static/svg/font-awesome