baseURL: "https://anton.ohorodnyk.name/"
languageCode: "en-us"
title: "Anton Ohorodnyk"
copyright: "Anton Ohorodnyk All Rights Reserved"

disableLanguages: true
enableGitInfo: false
enableRobotsTXT: true

Paginate: 10

taxonomies:
  tag: topics

disableKinds:
  - RSS
  - section

menu:
  main:
    - name: Home
      post:
      pre:
      url: /
      weight: 1
    - name: Topics
      post:
      pre:
      url: /topics
      weight: 2
    - name: About
      post:
      pre:
      url: /about
      weight: 3
    - name: Archive
      post:
      pre:
      url: /archive
      weight: 4

permalinks:
  posts: /:year/:month/:title/

params:
  author: Anton Ohorodnyk
  meta:
    favicon:
      version: 1

markup:
  highlight:
    anchorLineNos: true
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
    style: monokai
    tabWidth: 2
  tableOfContents:
    startLevel: 1
    endLevel: 2

module:
  imports:
    - path: github.com/necolas/normalize.css
      mounts:
        - source: normalize.css
          target: assets/css/normalize.css
    - path: github.com/FortAwesome/Font-Awesome
      mounts:
        - source: scss
          target: assets/fontawesome
        - source: webfonts
          target: static/fonts/fontawesome
